### ISSUE TITLE
When starting and closing

### ISSUE THREAD

**Issue by SoDoomed** [keithorange/AudioVideoFlipper_Imagination_Gym#2]
When pressing "Start" I receive this error message in CMD

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0\Lib\tkinter\__init__.py", line 1967, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "D:\Downloads\AudioVideoFlipper_Imagination_Gym\start_flipper_ui.py", line 181, in load_data_and_start_flipper
    flipper.toggle_flipping()
  File "D:\Downloads\AudioVideoFlipper_Imagination_Gym\av_flipper.py", line 222, in toggle_flipping
    self.start_flipping()
  File "D:\Downloads\AudioVideoFlipper_Imagination_Gym\av_flipper.py", line 231, in start_flipping
    self.run_flipping()
  File "D:\Downloads\AudioVideoFlipper_Imagination_Gym\av_flipper.py", line 265, in run_flipping
    self.set_system_volume(volume)
  File "D:\Downloads\AudioVideoFlipper_Imagination_Gym\av_flipper.py", line 207, in set_system_volume
    subprocess.call(
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0\Lib\subprocess.py", line 389, in call
    with Popen(*popenargs, **kwargs) as p:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified

And when trying to stop the program, I receive this error in CMD

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0\Lib\tkinter\__init__.py", line 1967, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "D:\Downloads\AudioVideoFlipper_Imagination_Gym\av_flipper.py", line 198, in confirm_exit
    self.stop_flipping()
  File "D:\Downloads\AudioVideoFlipper_Imagination_Gym\av_flipper.py", line 236, in stop_flipping
    self.set_system_volume(self.args.max_volume)
  File "D:\Downloads\AudioVideoFlipper_Imagination_Gym\av_flipper.py", line 207, in set_system_volume
    subprocess.call(
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0\Lib\subprocess.py", line 389, in call
    with Popen(*popenargs, **kwargs) as p:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by SoDoomed** [comment]
Nevermind, the error was simply caused by NirCmd.exe not being on my Windows 10 machine. After putting that file into my windows folder, there are no more errors.

You just need to update the requirements to include that file.

**Comment by keithorange** [comment]
Thanks! I accidently deleted that file due to someone telling me it was unecessary!
